/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connaccess;

import java.io.File;
import java.sql.*;
import static java.sql.DriverManager.println;
import java.util.ArrayList;

public class AddingOffice extends javax.swing.JFrame {

    private ArrayList<Office> office = new ArrayList<>();
    private ArrayList<Address> address = new ArrayList<>();
    
    private int selectIndex;
    private Connectionn conncetionClass = new Connectionn();
    private Connection conn = null;
    private Statement stRsOffice = null;
    private Statement stRsAddress = null;
    private Statement stRsUpdate = null;
    
    public AddingOffice() {//Конструктор по подразбиране

        initComponents();
        
        try {//Прихващане на изключения
            conn =  conncetionClass.getConn();
            stRsOffice = (Statement) conn.createStatement();
            stRsAddress = (Statement) conn.createStatement();
            stRsUpdate = (Statement) conn.createStatement();

            ResultSet rs = stRsOffice.executeQuery("SELECT * FROM Office");
            ResultSet rsAddress = stRsAddress.executeQuery("SELECT * FROM Адрес");
            int i = 0;
                        while (rs.next()) {//обхождаме всички записи
                office.add(new Office(rs.getInt(1),rs.getString(2), rs.getInt(3)));//използваме мутатора за да мутираме стойността на полето и да
                //добавим всички записи в него
 
                cmbSelectName.addItem(office.get(i).getName()); // Зареждане на текст в падащото меню
                i++;
            }
            
            i = 0;
            while (rsAddress.next()) {//обхождаме всички записи
                address.add(new Address(rsAddress.getInt(1), rsAddress.getString(2)));//използваме мутатора за да мутираме стойността на полето и да
                //добавим всички записи в него

                jComboBox1.addItem(address.get(i).getName()); // Зареждане на текст в падащото меню
                i++;
            }

            txtNewRec.setText("");

        } catch (Exception ex) {//обработка при грешка
            System.out.println(String.format("Exception: %s", ex.getMessage()));
            //извеждане на грешката като текст в скрия label
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNewRec = new javax.swing.JTextField();
        btnNewRec = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        cmbSelectName = new javax.swing.JComboBox<>();
        btnUpdateRec = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnShowName1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        txtNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRecActionPerformed(evt);
            }
        });

        btnNewRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewRec.setText("Въведи нов запис");
        btnNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Таблица за модифициране на офис");

        cmbSelectName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectNameItemStateChanged(evt);
            }
        });
        cmbSelectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbSelectNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbSelectNameMousePressed(evt);
            }
        });
        cmbSelectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectNameActionPerformed(evt);
            }
        });

        btnUpdateRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateRec.setText("Обнови избран запис");
        btnUpdateRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Име на офис:");

        lblTitle2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Адрес на офис:");

        lblTitle3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle3.setText("Модифициране име на офис:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connaccess/KATPoliceLogoBigger.png"))); // NOI18N

        btnShowName1.setText("Към главно меню");
        btnShowName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(412, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdateRec, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cmbSelectName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitle2)
                                    .addComponent(lblTitle3)
                                    .addComponent(txtNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitle1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowName1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle1)
                            .addComponent(btnShowName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSelectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lblTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnNewRec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateRec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecActionPerformed
        String name = txtNewRec.getText();//задаване на стойност на полето - взетата от txtNewRec
        String  add = (String) jComboBox1.getSelectedItem();
        int addr = 0;
        
        try {
            for(int i = 0; i < address.size(); i++){
                if(address.get(i).getName() == add){
                    addr = address.get(i).getId();
                }
            }

            String query = "INSERT INTO Office (Име, Адрес) VALUES('" + name + "', '" + addr + " ')";
            //Добавяща заявка на SQL

            stRsUpdate.executeUpdate(query);//Изпълняване на заявката
            lblError.setText("Successfull");//Ако е изпълнена - изведи текст на потребителя, че всичко е наред
        } catch (Exception ex) {
            lblError.setText(String.format("Exception: %s", ex.getMessage()));
        }

    }//GEN-LAST:event_btnNewRecActionPerformed

    private void cmbSelectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectNameActionPerformed

    }//GEN-LAST:event_cmbSelectNameActionPerformed

    private void cmbSelectNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSelectNameMouseClicked

    }//GEN-LAST:event_cmbSelectNameMouseClicked

    private void cmbSelectNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSelectNameMousePressed

    }//GEN-LAST:event_cmbSelectNameMousePressed

    private void cmbSelectNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectNameItemStateChanged
        //System.out.println(":O)");
        txtNewRec.setText(cmbSelectName.getSelectedItem().toString());
        selectIndex = cmbSelectName.getSelectedIndex();
        System.out.println(selectIndex);
    }//GEN-LAST:event_cmbSelectNameItemStateChanged

    private void btnUpdateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecActionPerformed
        
        try {

            //Добавяща заявка на SQL
            String  add = (String) jComboBox1.getSelectedItem();
            int addr = 0;

            for(int i = 0; i < address.size(); i++){
                if(address.get(i).getName() == add){
                    addr = address.get(i).getId();
                }
            }

            String query = "UPDATE Office SET  Име= '" + txtNewRec.getText() + "', Адрес= '" + addr + "' WHERE ID='" + office.get(selectIndex).getId() + "'";


            stRsUpdate.executeUpdate(query);//Изпълняване на заявката
            lblError.setText("Successfull");//Ако е изпълнена - изведи текст на потребителя, че всичко е наред
            
        } catch (Exception ex) {
            System.out.println(String.format("Exception: %s", ex.getMessage()));
        }


    }//GEN-LAST:event_btnUpdateRecActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRecActionPerformed

    private void btnShowName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName1ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_btnShowName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewRec;
    private javax.swing.JButton btnShowName1;
    private javax.swing.JButton btnUpdateRec;
    private javax.swing.JComboBox<String> cmbSelectName;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTextField txtNewRec;
    // End of variables declaration//GEN-END:variables
}
