/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connaccess;

import java.io.File;
import java.sql.*;
import static java.sql.DriverManager.println;
import java.util.ArrayList;


public class AddingOwnerOfCar extends javax.swing.JFrame {

    private ArrayList<Owner> owner = new ArrayList<>();
    private ArrayList<Address> address = new ArrayList<>();
    //private ArrayList<Car> volumeEngine = new ArrayList<>();
    
    private int selectIndex;
    private Connectionn conncetionClass = new Connectionn();
    private Connection conn = null;
    private Statement stRs = null;
    private Statement stRsAddress = null;
    private Statement stRsUpdate = null;

    public AddingOwnerOfCar() {//Конструктор по подразбиране

        initComponents();
        
        try {//Прихващане на изключения
            conn =  conncetionClass.getConn();
            stRs = (Statement) conn.createStatement();
            stRsAddress = (Statement) conn.createStatement();
            stRsUpdate = (Statement) conn.createStatement();

            ResultSet rs = stRs.executeQuery("SELECT * FROM OwnerOfCar ");
            ResultSet rsAddress = stRsAddress.executeQuery("SELECT * FROM Адрес ");
            int i = 0;
            while (rs.next()) {//обхождаме всички записи
                owner.add(new Owner(rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getInt(6)));//използваме мутатора за да мутираме стойността на полето и да
                //добавим всички записи в него
            }

            i = 0;
            while (rsAddress.next()) {//обхождаме всички записи
                address.add(new Address(rsAddress.getInt(1), rsAddress.getString(2)));//използваме мутатора за да мутираме стойността на полето и да
                //добавим всички записи в него
                jComboBox3.addItem(address.get(i).getName()); // Зареждане на текст в падащото меню
                i++;
            }

            txtNewRec.setText("");
            rs.close();
            rsAddress.close();   
        } catch (Exception ex) {//обработка при грешка
            System.out.println(String.format("Exception: %s", ex.getMessage()));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNewRec = new javax.swing.JTextField();
        btnNewRec = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        txtNewRec1 = new javax.swing.JTextField();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        txtNewRec2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        lblTitle5 = new javax.swing.JLabel();
        txtNewRec3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnShowName1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        txtNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRecActionPerformed(evt);
            }
        });

        btnNewRec.setText("Запиши резултат");
        btnNewRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Таблица за добавяне на собственици");

        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Име:");

        txtNewRec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRec1ActionPerformed(evt);
            }
        });

        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Фамилия:");

        lblTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle3.setText("ЕГН:");

        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("Телефон:");

        txtNewRec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRec2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        lblTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle5.setText("Адрес");

        txtNewRec3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRec3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connaccess/KATPoliceLogoBigger.png"))); // NOI18N

        btnShowName1.setText("Към главно меню");
        btnShowName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblTitle)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle2)
                            .addComponent(txtNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewRec3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle4)
                            .addComponent(txtNewRec2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle3)
                            .addComponent(lblTitle5)
                            .addComponent(btnNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewRec1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowName1)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitle)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewRec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNewRec3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNewRec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnNewRec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnShowName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecActionPerformed
        String name = txtNewRec.getText();//задаване на стойност на полето - взетата от txtNewRec
        String familiq = txtNewRec1.getText();//задаване на стойност на полето - взетата от txtNewRec
        String EGN = txtNewRec2.getText();//задаване на стойност на полето - взетата от txtNewRec
        String numb = txtNewRec3.getText();//задаване на стойност на полето - взетата от txtNewRec

        String  add = (String) jComboBox3.getSelectedItem();
        int addr = 0;
        
        try {
            for(int i = 0; i < address.size(); i++){
                if(address.get(i).getName() == add){
                    addr = address.get(i).getId();
                }
            }

            String query = "INSERT INTO OwnerOfCar ( Име, Фамилия, ЕГН, Телефон, Адрес) VALUES('" + name + " ', '" + familiq + " ', '" + EGN + " ', '" + numb + " ', '" + addr + " ')";
            //Добавяща заявка на SQL

            stRsUpdate.executeUpdate(query);//Изпълняване на заявката
            
        } catch (Exception ex) {
            System.out.println(String.format("Exception: %s", ex.getMessage()));
        }

    }//GEN-LAST:event_btnNewRecActionPerformed



    private void txtNewRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRecActionPerformed

    private void txtNewRec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRec1ActionPerformed

    private void txtNewRec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRec2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void txtNewRec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRec3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewRec3ActionPerformed

    private void btnShowName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName1ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingOwnerOfCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewRec;
    private javax.swing.JButton btnShowName1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JTextField txtNewRec;
    private javax.swing.JTextField txtNewRec1;
    private javax.swing.JTextField txtNewRec2;
    private javax.swing.JTextField txtNewRec3;
    // End of variables declaration//GEN-END:variables
}
