/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connaccess;

import java.io.File;
import static java.lang.Integer.parseInt;
import java.sql.*;
import static java.sql.DriverManager.println;
import java.util.ArrayList;


public class MainMenu extends javax.swing.JFrame {

    private ArrayList<Car> cars = new ArrayList<>();
    private ArrayList<BrandCar> brands = new ArrayList<>();
    private ArrayList<ModelOfCar> models = new ArrayList<>();

    //private ArrayList<Car> volumeEngine = new ArrayList<>();
    
    private int selectIndex;

    public MainMenu() {//Конструктор по подразбиране

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnShowName = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnShowName1 = new javax.swing.JButton();
        btnShowName2 = new javax.swing.JButton();
        btnShowName3 = new javax.swing.JButton();
        btnShowName4 = new javax.swing.JButton();
        btnShowName5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        btnShowName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowName.setText("Добавяне на коли");
        btnShowName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowNameActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Главно меню");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connaccess/KATPoliceLogoBigger.png"))); // NOI18N

        btnShowName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowName1.setText("Добавяне на собственици");
        btnShowName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName1ActionPerformed(evt);
            }
        });

        btnShowName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowName2.setText("Добавяне на служители");
        btnShowName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName2ActionPerformed(evt);
            }
        });

        btnShowName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowName3.setText("Преглед на отчет");
        btnShowName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName3ActionPerformed(evt);
            }
        });

        btnShowName4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowName4.setText("Добавяне на Офиси");
        btnShowName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName4ActionPerformed(evt);
            }
        });

        btnShowName5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowName5.setText("Регистрация на автомобили");
        btnShowName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblTitle)
                        .addGap(165, 165, 165))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowName3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowName5))
                        .addGap(25, 25, 25)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnShowName1)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowName4)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowName2)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowName5)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowName3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowNameActionPerformed
        this.dispose();
        new AddingCar().setVisible(true);
    }//GEN-LAST:event_btnShowNameActionPerformed

    private void btnShowName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName1ActionPerformed
        this.dispose();
        new AddingOwnerOfCar().setVisible(true);
    }//GEN-LAST:event_btnShowName1ActionPerformed

    private void btnShowName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName2ActionPerformed
        this.dispose();
        new AddingEmployee().setVisible(true);
    }//GEN-LAST:event_btnShowName2ActionPerformed

    private void btnShowName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName3ActionPerformed
        this.dispose();
        new ReportRegisterNewCar().setVisible(true);
    }//GEN-LAST:event_btnShowName3ActionPerformed

    private void btnShowName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName4ActionPerformed
        this.dispose();
        new AddingOffice().setVisible(true);
    }//GEN-LAST:event_btnShowName4ActionPerformed

    private void btnShowName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName5ActionPerformed
        this.dispose();
        new RegisterNewCar().setVisible(true);
    }//GEN-LAST:event_btnShowName5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowName;
    private javax.swing.JButton btnShowName1;
    private javax.swing.JButton btnShowName2;
    private javax.swing.JButton btnShowName3;
    private javax.swing.JButton btnShowName4;
    private javax.swing.JButton btnShowName5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
