/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connaccess;

import java.awt.print.PrinterException;
import java.io.File;
import static java.lang.Float.parseFloat;
import java.sql.*;
import static java.sql.DriverManager.println;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ReportRegisterNewCar extends javax.swing.JFrame {

    private ArrayList<Owner> owner = new ArrayList<>();
    
    private ArrayList<RegisterNewCarObject> registration = new ArrayList<>();
    private ArrayList<Car> cars = new ArrayList<>();
    private ArrayList<BrandCar> brand = new ArrayList<>();
    private ArrayList<ModelOfCar> model = new ArrayList<>();
    private ArrayList<Integer> regCar = new ArrayList<>();
    

    //private ArrayList<Car> volumeEngine = new ArrayList<>();
     
    private int selectIndex;
    private String str = "";
    
    private Connectionn conncetionClass = new Connectionn();
    private Connection conn = null;
    private Statement stRsOwnerOfCar = null;
    private Statement stRsCar = null;
    private Statement stRsCarModel = null;
    private Statement stRsCarBrand = null;
    private Statement stRsSelect = null;
    private Statement stRsUpdate = null;

    public ReportRegisterNewCar() {//Конструктор по подразбиране

        initComponents();
        try {//Прихващане на изключения
            
            conn =  conncetionClass.getConn();
            stRsOwnerOfCar = (Statement) conn.createStatement();
            stRsCar = (Statement) conn.createStatement();
            stRsCarBrand = (Statement) conn.createStatement();
            stRsCarModel = (Statement) conn.createStatement();
            stRsSelect = (Statement) conn.createStatement();
            stRsUpdate = (Statement) conn.createStatement();
            
            ResultSet rs = stRsOwnerOfCar.executeQuery("SELECT * FROM OwnerOfCar");
            //Селектираща заявка на SQL, където в квадратните скоби са "Име" - колоната която искаме и "Потребител" - таблицата
            int i = 0;
            while (rs.next()) {//обхождаме всички записи
                owner.add(new Owner(rs.getInt(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getInt(6)));//използваме мутатора за да мутираме стойността на полето и да
                //добавим всички записи в него
                jComboBox4.addItem(owner.get(i).getName()); // Зареждане на текст в падащото меню
                i++;
            }
      
        } catch (Exception ex) {//обработка при грешка
            System.out.println(String.format("Exception: %s", ex.getMessage()));
            //извеждане на грешката като текст в скрия label
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnShowName1 = new javax.swing.JButton();
        btnShowName2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Отчет по име на собственик");

        lblTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Собственик:");

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connaccess/KATPoliceLogoBigger.png"))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnShowName1.setText("Към главно меню");
        btnShowName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName1ActionPerformed(evt);
            }
        });

        btnShowName2.setText("Print");
        btnShowName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowName2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblTitle1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnShowName2)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowName1)
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowName2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShowName1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)))
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        
        
        jTextArea1.setText(""); // Зареждане на текст в падащото меню
        cars.clear(); 
        registration.clear();
        model.clear();
        brand.clear();
        regCar.clear();
        
        String wholeTextReport = "";
        
          try {//Прихващане на изключения
            int name_id = 0;
            
            for(int i = 0; i < owner.size();i++){
                if(jComboBox4.getSelectedItem() == owner.get(i).getName()){
                    name_id = owner.get(i).getId();
                }
            }
            ResultSet rs = stRsSelect.executeQuery("SELECT Car_id, Price_of_registration \n" +
            "FROM RegistrationOfCar WHERE OwnerOfCar_id = "+name_id);
            ResultSet rsCarModel = stRsCarModel.executeQuery("SELECT * \n" +
            "FROM ModelOfCar");
            //Селектираща заявка на SQL за записите, които са само за дадения клиент
            int i = 0;
            while (rs.next()) {//обхождаме всички записи
                registration.add(new RegisterNewCarObject(rs.getInt(1), rs.getDouble(2)));//използваме мутатора за да мутираме стойността на полето и да
                //добавим всички записи в него
                regCar.add(registration.get(i).getCar_Id());
                i++;
            }
            str = "";
            for(i = 0; i <regCar.size(); i++){
                str += " Id=" + regCar.get(i);
               
                if(i < regCar.size()-1){
                    str += " OR ";
                }
            }
            String query = "SELECT ID, Power, Volume, Brand_Id, Model_Id  FROM Car WHERE"+str;
            ResultSet rsCar = stRsCar.executeQuery(query);
            
            //Взима информация от базата данни от таблици от базата данни
            i=0;
            while (rsCar.next()) {//обхождаме всички записи
                cars.add(new Car(rsCar.getInt(1), rsCar.getInt(2), rsCar.getInt(3), rsCar.getInt(4), rsCar.getInt(5)));//използваме мутатора за да мутираме стойността на полето и да
                i++;
            }
            
            int j = 0;
            ResultSet rsCarBrand = stRsCarBrand.executeQuery("SELECT * \n" +
            "FROM BrandCar");
            while (rsCarBrand.next()) {//обхождаме всички записи
                brand.add(new BrandCar(rsCarBrand.getInt(1), rsCarBrand.getString(2)));//използваме мутатора за да мутираме стойността на полето и да
                j++;
            }

            int k = 0;
            while (rsCarModel.next()) {//обхождаме всички записи
                model.add(new ModelOfCar(rsCarModel.getInt(1), rsCarModel.getString(2)));//използваме мутатора за да мутираме стойността на полето и да
                k++;
            }

                       
            wholeTextReport = "Кола - Цена \n";
            double totalPrice = 0;
            String brandCar = "";
            String modelCar = "";
            // Търси за бранда и модела на колата от базата данни 
            for(int q = 0; q < cars.size(); q++){
                for(int p = 0; p < brand.size(); p++){
                    if(cars.get(q).getMark() == brand.get(p).getId()){
                        brandCar =  brand.get(p).getName();
                    }
                }
                for(int p = 0; p < model.size(); p++){
                    
                    if(cars.get(q).getModel() == model.get(p).getId()){
                        modelCar =  model.get(p).getName();
                    }
                }
                
                wholeTextReport += brandCar + " " + modelCar +"- "+registration.get(q).getPriceOfRegistration() + " лв.\n";
                totalPrice += registration.get(q).getPriceOfRegistration();
            }
            
            jTextArea1.setText(wholeTextReport + "Total price: "+ totalPrice); // Зареждане на текст в падащото меню
        } catch (Exception ex) {//обработка при грешка
            System.out.println(String.format("Exception: %s", ex.getMessage()));
            //извеждане на грешката като текст conosole
        }

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btnShowName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName1ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowName1ActionPerformed

    private void btnShowName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowName2ActionPerformed
        try {
            jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(ReportRegisterNewCar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnShowName2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportRegisterNewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportRegisterNewCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowName1;
    private javax.swing.JButton btnShowName2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}


